# Generated by Django 2.0.1 on 2018-04-10 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify_key', models.UUIDField(verbose_name='identify key')),
                ('data', models.BinaryField(verbose_name='data')),
                ('add_dt', models.DateTimeField(auto_now=True, verbose_name='date and time of adding')),
                ('delete_dt', models.DateTimeField(null=True, verbose_name='date and time of deleting')),
                ('total_times', models.IntegerField(null=True, verbose_name='times of opening total')),
                ('actual_times', models.IntegerField(null=True, verbose_name='times of opening')),
                ('init_vector', models.BinaryField(blank=True, null=True, verbose_name='initial vector')),
                ('db_key', models.TextField(verbose_name='code from database')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encrypted_data', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
